### ISSUE TITLE
Newly created playlists cannot be loaded in BeatSaber 1.37.0

### ISSUE THREAD

**Issue by culage** [exelix11/QuestSongManager#1]
Playlists newly created by QuestSongManager v1.5-1 are not displayed in-game on BeatSaber 1.37.0 (2024-07-15, songcore mod v1.1.14, playlistcore mod v1.4.2).

The cause of the problem seems to be `"customData":null` in the playlist JSON. If you rewrite that part in a text editor to `"customData": {"syncURL": null}`, the playlist will now be displayed in-game.

This could be an issue on the PlaylistCore mod side. It might be better to wait for the PlaylistCore mod to fix it...

\# This amazing tool always helps me. Thank you.

**Comment by exelix11** [comment]
Yeah it's probably a bug in PlaylistCore, just in case i'll make sure to remove the custom data object if it's null from the serialization, that should make their json parsing always work

**Comment by exelix11** [comment]
I implemented this in latest commit, you can get an auto build from github actions [here](https://github.com/exelix11/QuestSongManager/actions/runs/9936393380) when it's ready.  Let me know if this fixes it.

**Comment by culage** [comment]
That's great!
A new playlist is now available in-game.
Meny thanks.
